version: "3.9"
services:
        qbittorrent:
                image: lscr.io/linuxserver/qbittorrent:latest
                container_name: qbittorrent
                environment:
                        - PGID=1000
                        - PUID=1000
                        - TZ=Canada/Newfoundland
                        - WEBUI_PORT=8080
                volumes:
                        - /home/akash/qbittorrent:/config
                        - /home/akash/media:/downloads
                ports:
                        - 8080:8080
                        - 6881:6881
                        - 6881:6881/udp
                restart: unless-stopped
