version: "3.9"
services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: "EST5EDT"
      USERID: 1000
      GROUPID: 1000
    networks:
      - default
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
        # read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/akash/media:/mnt:z
    command: '-s "barracuda;/mnt;yes;no" -n -u "akash;akash" -p'

networks:
  default:
